status = [
  "ci 1.8.5 - ubuntu-latest",
  "ci 1.8.5 - macOS-latest",
  "ci 1.8.5 - windows-latest",
  "buildkite/kinematic1d-dot-jl-ci",
  "docbuild",
  "format",
]
delete_merged_branches = true
timeout_sec = 10800
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
